//
// Created by Marcel Beyer on 22.08.2023.
//

#ifndef GENETIC_ALGORITHM_VLSI_V2_INITIALISE_H
#define GENETIC_ALGORITHM_VLSI_V2_INITIALISE_H

#endif //GENETIC_ALGORITHM_VLSI_V2_INITIALISE_H

void load_data_f1();